// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpuMmqdgY-XJhsCwDB5CWvzVPdeE_b1Pc',
    appId: '1:873469841792:web:0aad1aba2738f091c3b165',
    messagingSenderId: '873469841792',
    projectId: 'phoneauth-dbe59',
    authDomain: 'phoneauth-dbe59.firebaseapp.com',
    storageBucket: 'phoneauth-dbe59.appspot.com',
    measurementId: 'G-J5XYB6Q3PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEVVlsTUXxq7BzQcK-WFICkLrEw-yvUZA',
    appId: '1:873469841792:android:929769c65c2d0c98c3b165',
    messagingSenderId: '873469841792',
    projectId: 'phoneauth-dbe59',
    storageBucket: 'phoneauth-dbe59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn5t2cCWPeVXqzloE2ahvtACVPfQ3ksgM',
    appId: '1:873469841792:ios:2cf1c4d22c04eb46c3b165',
    messagingSenderId: '873469841792',
    projectId: 'phoneauth-dbe59',
    storageBucket: 'phoneauth-dbe59.appspot.com',
    iosBundleId: 'com.example.fuelease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn5t2cCWPeVXqzloE2ahvtACVPfQ3ksgM',
    appId: '1:873469841792:ios:2cf1c4d22c04eb46c3b165',
    messagingSenderId: '873469841792',
    projectId: 'phoneauth-dbe59',
    storageBucket: 'phoneauth-dbe59.appspot.com',
    iosBundleId: 'com.example.fuelease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpuMmqdgY-XJhsCwDB5CWvzVPdeE_b1Pc',
    appId: '1:873469841792:web:a9f3bbf66308def5c3b165',
    messagingSenderId: '873469841792',
    projectId: 'phoneauth-dbe59',
    authDomain: 'phoneauth-dbe59.firebaseapp.com',
    storageBucket: 'phoneauth-dbe59.appspot.com',
    measurementId: 'G-VT7HQW8VLW',
  );
}
